yii/common/models/ApiEpn.php
<?php
namespace common\models;

class ApiEpn
{
    const EPN_API_URL = 'http://api.epn.bz/json';
    const EPN_CLIENT_API_VERSION = 2;

    // Параметры
    private $user_api_key = '';
    private $user_hash = '';
    private $prepared_requests = [];
    private $request_results = [];
    private $last_error = '';
    private $last_error_type = 'none';
    //======================================================================
    // Конструктор
    public function __construct($user_api_key = '', $user_hash = '')
    {
        $this->user_api_key = $user_api_key;
        $this->user_hash = $user_hash;
    }
    //======================================================================

    //======================================================================
    // Добавление запроса в список
    private function AddRequest($name, $action, $params = [])
    {
        // Нормализуем входные данные
        if (!is_array($params)) {
            $params = [];
        }

        $params['action'] = $action;
        $this->prepared_requests[$name] = $params;
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Добавление запроса на получение списка категорий
    public function AddRequestCategoriesList($name, $lang = 'ru')
    {
        $this->AddRequest(
            $name,
            'list_categories',
            [
                'lang' => $lang
            ]
        );
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Добавление запроса на получение списка категорий
    public function AddRequestCurrenciesList($name)
    {
        $this->AddRequest(
            $name,
            'list_currencies',
            []
        );
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Запрос на поиск
    public function AddRequestSearch($name, $options = array())
    {
        // Добавляем запрос в список
        $this->AddRequest($name, 'search', $options);
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Запрос на получение количества товаров в категориях
    public function AddRequestCountForSearch($name, $options = array())
    {
        // Добавляем запрос в список
        $this->AddRequest($name, 'count_for_categories', $options);
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Запрос на получение информации о товаре
    public function AddRequestGetOfferInfo($name, $id, $lang = 'ru', $currency = 'RUR')
    {
        // На всякий случай Нормализуем то что на входе
        // intval не используем в связи с проблемами на 32-битных системах
        $id = preg_replace('{[^\d]+}ui', '', $id);
        if ($id == '') $id = 0;
        // Добавим запрос в список
        $this->AddRequest(
            $name,
            'offer_info',
            array(
                'id' => $id,
                'lang' => $lang,
                'currency' => $currency,
            )
        );
        return TRUE;
    }
    //======================================================================

    //======================================================================
    // Получение топовых товаров
    public function AddRequestGetTopMonthly($name, $lang = 'ru', $currency = 'RUR', $orderby = 'sales', $category = '')
    {
        $this->AddRequest(
            $name,
            'top_monthly',
            array(
                'lang' => $lang,
                'currency' => $currency,
                'orderby' => $orderby,
                'category' => $category,
            )
        );
    }
    //======================================================================

    //======================================================================
    // Выполнение всех запросов
    public function RunRequests()
    {
        // Сбрасываем переменные
        $this->request_results = array();
        $this->last_error = '';
        $this->last_error_type = 'none';

        // Если список запросов пуст
        if (!sizeof($this->prepared_requests)) {
            return TRUE;
        }

        // Структура для отправки запросса
        $data = array(
            'user_api_key' => $this->user_api_key,
            'user_hash' => $this->user_hash,
            'api_version' => self::EPN_CLIENT_API_VERSION,
            'requests' => $this->prepared_requests,
        );
        //print_r($this->prepared_requests);
        // Строка запроса
        $post_data = json_encode($data);

        // Будем использовать cURL
        $ch = curl_init();
        // Выполняем запрос
        curl_setopt($ch, CURLOPT_URL, self::EPN_API_URL);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: text/plain'));
        $result = curl_exec($ch);
        $curl_error_msg = curl_error($ch);
        //print "<!-- $curl_error_msg\n\n$result -->\n";
        // Если http-запрос обработан с ошибкой
        if ($curl_error_msg != '') {

            $this->last_error = $curl_error_msg;
            $this->last_error_type = 'network';
        } else {
            // Парсим данные
            $result_data = json_decode($result, TRUE);
            $this->last_error = isset($result_data['error']) ? $result_data['error'] : '';
            if ($this->last_error != '') {
                $this->last_error_type = 'data';
            }
            $this->request_results = isset($result_data['results']) && is_array($result_data['results']) ? $result_data['results'] : array();
        }
        // Независимо от результата сбрасываем список запросов
        $this->prepared_requests = array();
        // Если не было ошибок то всё хорошо
        return $this->last_error == '' ? TRUE : FALSE;

    }
    //======================================================================

    //======================================================================
    // Получение отклика
    public function GetRequestResult($name)
    {
        return isset($this->request_results[$name]) ? $this->request_results[$name] : [];
    }

    //======================================================================


    /**
     *
     */
    public function clearResult()
    {
        $this->request_results = [];
    }

    /**
     *
     */
    public function clearRequests()
    {
        $this->prepared_requests = [];
    }


    //======================================================================
    // Информация о последней ошибке
    public function LastError()
    {
        return $this->last_error;
    }
    //======================================================================
    //======================================================================
    // Информация о типе последней ошибки
    public function LastErrorType()
    {
        return $this->last_error_type;
    }

    //======================================================================

    public function getResult()
    {
        return $this->request_results;
    }

    public function getRequests()
    {
        return $this->prepared_requests;
    }
}

yii/common/models/Categories.php
<?php

namespace common\models;

use common\system\Helper;
use common\system\PModel;
use Yii;

/**
 * This is the model class for table "categories".
 *
 * @property int $category_id
 * @property string $created_at
 * @property string $name
 * @property string $img
 * @property int $parent_id
 * @property boolean $popular
 *
 * @property CategoryItems[] $categoryItems
 */
class Categories extends \yii\db\ActiveRecord
{

    const POPULAR = 1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at'], 'safe'],
//            [['name', 'img', 'parent_id'], 'required'],
            [['parent_id'], 'integer'],
            [['name', 'img'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'category_id' => 'Category ID',
            'created_at' => 'Created At',
            'name' => 'Name',
            'img' => 'Img',
            'parent_id' => 'Parent ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryItems()
    {
        return $this->hasMany(CategoryItems::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return array
     */
    public static function getList()
    {
        $model = self::find()->all();

        $result = [];
        /** @var Categories $item */
        foreach ($model as $item) {
            $result['list'][$item->category_id] = $item->name;

            if ($item->popular) {
                $result['popular'][$item->category_id] = $item->name;
            }
        }

        return $result;
    }

    /**
     * @return array|mixed
     */
    public function getTree()
    {
        $items = self::find()->asArray()->all();
        return $this->buildTree($items);
    }

    /**
     * @param $elements
     * @param int $parentId
     * @return array
     */
    public function buildTree(array $elements, $parentId = 0)
    {
        $branch = [];
        foreach ($elements as $element) {
            if ($element['parent_id'] == $parentId) {
                $children = $this->buildTree($elements, $element['category_id']);
                if ($children) {
                    $element['children'] = $children;
                }
                $branch[] = $element;
            }
        }
        return $branch;
    }

    /**
     * @param array $elements
     */
    public function buildTreeHtml(array $elements)
    {

        echo '<ul>';
        foreach ($elements as $element) {

            $popular = (self::POPULAR == $element['popular']) ? 'glyphicon glyphicon-star' : '';

            echo '<li data-jstree=\'{"icon":"' . $popular . '"}\' data-id = ' . $element['category_id'] . '>' . $element['name'];
            if (isset($element['children'])) {
                $this->buildTreeHtml($element['children']);
            }
            echo '</li><i class="' . $popular . '"></i>';
        }
        echo '</ul>';
    }

    /**
     * @return bool
     */
    public function popular()
    {
        $this->popular = (self::POPULAR == $this->popular) ? 0 : self::POPULAR;
        return $this->save();
    }
}

yii/common/models/CategoryItems.php
<?php

namespace common\models;

use common\system\PModel;
use Yii;

/**
 * This is the model class for table "category_items".
 *
 * @property int $category_id
 * @property int $shop_category_id
 *
 * @property Categories $category
 * @property ShopCategories $shopCategory
 */
class CategoryItems extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category_items';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'shop_category_id'], 'required'],
            [['category_id', 'shop_category_id'], 'integer'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Categories::className(), 'targetAttribute' => ['category_id' => 'category_id']],
            [['shop_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ShopCategories::className(), 'targetAttribute' => ['shop_category_id' => 'shop_category_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'category_id' => 'Category ID',
            'shop_category_id' => 'Shop Category ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Categories::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShopCategory()
    {
        return $this->hasOne(ShopCategories::className(), ['shop_category_id' => 'shop_category_id']);
    }
}

yii/common/models/LoginForm.php
<?php
namespace common\models;

use Yii;
use yii\base\Model;

/**
 * Login form
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();
            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     *
     * @return bool whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600 * 24 * 30 : 0);
        }
        
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    protected function getUser()
    {
        if ($this->_user === null) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

yii/common/models/OffersId.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "offers_id".
 *
 * @property int $offer_id_id
 * @property int $offer_id
 * @property int $day
 */
class OffersId extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'offers_id';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'offer_id_id' => 'Offer Id ID',
            'offer_id' => 'Offer ID',
            'day' => 'Day',
        ];
    }
}

yii/frontend/controllers/ApiController.php
<?php
namespace frontend\controllers;

use common\models\Offers;

use yii\web\Controller;
use yii\data\Pagination;
use yii\web\Response;

class ApiController extends Controller
{
    /**
     * @return array
     */
    public function actionSales()
    {
        $querySales = Offers::find()->where('sales IS NOT NULL');
        $countQuerySales = clone $querySales;
        $pagesSale = new Pagination(['totalCount' => $countQuerySales->count(), 'defaultPageSize' => 6]);
        $modelsSale = $querySales->offset($pagesSale->offset)
            ->limit($pagesSale->limit)
            ->all();

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return (new Offers())->getSalesList($modelsSale);
    }

    /**
     * @return array
     */
    public function actionNew()
    {
        $queryTop = Offers::find()->where('new IS NOT NULL');
        $countQueryTop = clone $queryTop;
        $pagesTop = new Pagination(['totalCount' => $countQueryTop->count(), 'defaultPageSize' => 6]);
        $modelsTop = $queryTop->offset($pagesTop->offset)
            ->limit($pagesTop->limit)
            ->all();

        \Yii::$app->response->format = Response::FORMAT_JSON;
        return (new Offers())->getSalesList($modelsTop);
    }

    /**
     * @param string $q
     * @param int $pages
     * @return array
     */
    public function actionSearch($q = '', $pages = 0)
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return (new Offers())->getDropListByName($q, $pages);
    }

    /**
     * @param array $data
     * @return array|string
     */
    public function actionOffers(array $data = [])
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;

        /** @var Offers $model */
        $model = (new  Offers)->getSearchOffers($data);
        return (new  Offers)->getSalesList($model);
    }
}

yii/frontend/views/common/head.php
<?php

use \yii\helpers\Url;
use kartik\nav\NavX;
use \yii\web\JsExpression;
use kartik\icons\Icon;

Icon::map($this, Icon::FA);
Icon::map($this, Icon::OI);
Icon::map($this, Icon::EL);

$formatJs = <<< 'JS'
var formatRepo = function (repo) {
    if (repo.loading) {
        return repo.text;
    }
    var markup =
'<a target="_blank" href="' + repo.url + '"><div class="row hover-link">' + 
    '<div class="col-sm-5">' +
        '<img src="' + repo.picture + '" class="img-rounded" style="width:50px" />' +
        '<span style="margin-left:5px;font-family: none;font-size: 14px;">' + repo.name + '</span>' + 
    '</div>' +
    '<div class="col-sm-3"><b style="font-size: 20px;color: #000;"> ' + form.formatPriceCurrency(repo.price, 'RUR') + '</b></div>' +
    '<div class="col-sm-3"><img src="' + repo.logos + '" class="img-rounded" style="width:100px" /></div>' +
'</div></a>';
    
    return '<div style="overflow:hidden;">' + markup + '</div>';
};
var formatRepoSelection = function (repo) {
    return repo.name;
}
JS;

$this->registerJs($formatJs, \yii\web\View::POS_HEAD);
?>

<header class="no-padding-bottom header-alt">
    <div class="container no-padding">
        <div class="col-xs-12 col-md-3 logo-holder">
            <div class="logo">
                <a href="<?= Url::to(['/site']); ?>">
                    <svg width="233px" height="54px" viewBox="0 0 233 54" version="1.1"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill="#ffffff" d=" M 0.00 0.00 L 233.00 0.00 L 233.00 54.00 L 0.00 54.00 L 0.00 0.00 Z"/>
                        <path class="logo-svg"
                              d=" M 104.82 6.46 C 107.74 5.13 110.66 3.80 113.58 2.46 C 113.59 18.71 113.59 34.95 113.59 51.20 C 110.65 51.20 107.71 51.20 104.78 51.20 C 104.84 50.67 104.96 49.62 105.02 49.09 C 100.02 53.56 91.66 52.69 87.37 47.67 C 84.80 44.83 83.96 40.97 83.20 37.33 C 75.63 37.37 68.05 37.26 60.47 37.40 C 61.41 39.88 62.49 42.75 65.24 43.71 C 69.03 45.31 73.10 43.58 75.89 40.91 C 77.67 42.73 79.47 44.54 81.22 46.40 C 75.60 52.47 65.66 53.95 58.77 49.23 C 53.06 45.18 51.58 37.52 52.30 30.95 C 52.75 25.29 55.84 19.51 61.29 17.27 C 66.83 15.00 73.85 15.40 78.54 19.37 C 81.58 21.92 82.87 25.85 83.50 29.64 C 84.32 24.24 87.32 18.69 92.71 16.75 C 96.83 15.07 101.64 15.89 104.93 18.89 C 104.77 14.75 104.83 10.60 104.82 6.46 Z"/>
                        <path class="logo-svg"
                              d=" M 118.44 3.44 C 121.37 1.09 126.26 3.21 126.52 6.97 C 127.17 10.89 122.39 14.12 119.00 12.03 C 115.74 10.46 115.39 5.41 118.44 3.44 Z"/>
                        <path class="logo-svg"
                              d=" M 10.22 19.63 C 14.71 14.58 23.51 14.56 27.42 20.34 C 33.58 13.24 48.54 14.42 50.33 24.80 C 51.41 33.54 50.55 42.41 50.82 51.20 C 47.88 51.20 44.94 51.20 42.00 51.20 C 41.92 44.09 42.14 36.97 41.93 29.87 C 41.95 27.41 40.48 24.57 37.76 24.43 C 34.66 23.72 30.88 25.51 30.74 29.01 C 30.35 36.39 30.71 43.80 30.59 51.20 C 27.67 51.20 24.75 51.20 21.82 51.20 C 21.74 44.12 21.98 37.04 21.73 29.96 C 21.79 27.24 19.97 24.22 16.95 24.37 C 13.91 23.84 10.58 25.90 10.49 29.15 C 10.13 36.49 10.47 43.85 10.35 51.20 C 7.43 51.20 4.51 51.20 1.59 51.20 C 1.59 39.69 1.59 28.18 1.59 16.67 C 4.53 16.67 7.47 16.67 10.41 16.67 C 10.36 17.41 10.27 18.89 10.22 19.63 Z"/>
                        <path class="logo-svg"
                              d=" M 129.25 19.84 C 135.49 16.15 143.23 14.75 150.23 16.89 C 154.92 18.35 157.47 23.34 157.42 28.02 C 157.56 35.75 157.42 43.47 157.47 51.20 C 154.57 51.20 151.68 51.20 148.79 51.20 C 148.84 50.65 148.93 49.56 148.98 49.01 C 144.10 52.49 137.26 53.09 132.09 49.91 C 126.05 46.27 125.51 36.43 131.16 32.19 C 136.26 28.22 143.30 28.77 149.13 30.64 C 148.62 28.53 148.91 25.65 146.65 24.49 C 141.77 22.26 136.27 24.40 131.93 26.90 C 131.04 24.55 130.14 22.19 129.25 19.84 Z"/>
                        <path class="logo-svg"
                              d=" M 117.06 16.67 C 119.98 16.67 122.90 16.67 125.82 16.67 C 125.82 28.18 125.82 39.69 125.82 51.20 C 122.90 51.20 119.98 51.20 117.06 51.20 C 117.06 39.69 117.06 28.18 117.06 16.67 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 201.86 17.62 C 202.52 17.30 203.82 16.67 204.48 16.35 C 204.48 18.10 204.48 19.84 204.48 21.59 C 205.23 21.59 206.73 21.60 207.48 21.60 C 207.48 22.17 207.48 23.30 207.48 23.86 C 206.73 23.87 205.22 23.89 204.47 23.91 C 204.49 26.42 204.34 28.95 204.62 31.45 C 205.86 32.02 207.13 32.53 208.42 32.99 C 206.71 34.03 204.25 35.64 202.51 33.72 C 201.29 30.65 202.08 27.15 201.88 23.91 C 201.39 23.89 200.42 23.87 199.94 23.86 C 199.94 23.30 199.94 22.18 199.94 21.62 C 200.43 21.60 201.41 21.57 201.90 21.56 C 201.88 20.24 201.87 18.93 201.86 17.62 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 169.01 34.60 C 161.80 34.48 161.85 21.38 169.03 21.30 C 171.56 20.91 173.24 22.99 174.55 24.80 C 172.38 25.03 170.35 23.99 168.21 24.05 C 165.19 25.78 165.69 32.04 169.72 32.24 C 171.04 30.86 172.68 30.26 174.58 30.81 C 173.29 32.73 171.68 35.03 169.01 34.60 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 176.14 24.15 C 177.71 20.91 182.63 20.34 185.06 22.88 C 186.61 24.47 186.37 26.86 186.72 28.88 C 183.63 28.96 180.54 28.94 177.46 29.07 C 178.33 30.06 178.74 31.71 180.15 32.08 C 182.15 31.99 184.30 31.15 185.94 32.84 C 183.84 33.87 181.50 35.30 179.09 34.28 C 175.09 32.89 174.46 27.52 176.14 24.15 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 188.27 21.67 C 191.44 22.12 195.65 20.04 197.89 23.12 C 199.40 26.61 198.50 30.58 198.71 34.28 C 197.84 34.27 196.97 34.27 196.10 34.26 C 196.04 31.26 196.36 28.21 195.84 25.24 C 195.30 22.95 190.93 23.34 191.03 25.84 C 190.71 28.63 190.93 31.46 190.90 34.27 C 190.25 34.27 188.94 34.27 188.28 34.27 C 188.28 30.07 188.28 25.87 188.27 21.67 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 209.34 24.33 C 210.88 20.80 216.32 20.24 218.67 23.23 C 219.85 24.84 219.70 26.96 220.06 28.84 C 216.93 28.95 213.79 28.96 210.67 29.17 C 211.42 30.17 212.14 31.20 213.03 32.08 C 214.53 32.45 215.99 31.66 217.44 31.37 C 217.81 31.81 218.56 32.68 218.93 33.11 C 216.82 34.02 214.49 35.28 212.18 34.20 C 208.39 32.73 207.86 27.62 209.34 24.33 Z"/>
                        <path fill="#3a3a3a"
                              d=" M 221.57 21.68 C 224.18 22.17 229.35 19.73 229.26 23.99 C 227.69 24.37 225.10 23.31 224.48 25.41 C 223.89 28.32 224.25 31.33 224.17 34.27 C 223.52 34.27 222.23 34.27 221.58 34.27 C 221.58 30.07 221.58 25.88 221.57 21.68 Z"/>
                        <path fill="#ffffff"
                              d=" M 177.47 26.72 C 178.35 25.45 179.09 23.45 180.99 23.60 C 182.85 23.48 183.54 25.46 184.45 26.68 C 182.12 26.79 179.79 26.80 177.47 26.72 Z"/>
                        <path fill="#ffffff"
                              d=" M 210.63 26.63 C 211.70 25.38 212.59 23.21 214.62 23.63 C 216.40 23.58 216.80 25.59 217.66 26.73 C 215.32 26.80 212.97 26.77 210.63 26.63 Z"/>
                        <path fill="#ffffff"
                              d=" M 60.57 29.87 C 61.45 26.41 64.15 23.26 68.04 23.58 C 71.91 23.17 74.23 26.62 75.30 29.84 C 70.39 29.99 65.48 29.97 60.57 29.87 Z"/>
                        <path fill="#ffffff"
                              d=" M 96.52 24.70 C 99.50 23.55 102.54 25.02 104.87 26.85 C 104.80 31.61 104.80 36.38 104.86 41.14 C 102.46 43.09 99.18 44.42 96.17 43.02 C 92.82 41.46 91.99 37.36 91.96 34.01 C 91.89 30.51 92.82 26.06 96.52 24.70 Z"/>
                        <path fill="#ffffff"
                              d=" M 137.58 37.63 C 141.09 35.82 145.16 36.85 148.82 37.59 C 148.82 38.98 148.80 40.38 148.79 41.78 C 145.51 43.89 141.25 45.34 137.54 43.42 C 135.23 42.33 135.28 38.72 137.58 37.63 Z"/>
                        <path class="logo-svg"
                              d=" M 163.30 39.16 C 165.64 38.00 168.47 38.66 171.01 38.49 C 172.96 38.53 176.17 38.23 176.35 40.94 C 176.51 46.79 170.77 51.96 165.05 51.93 C 161.43 51.79 162.41 47.39 162.23 44.97 C 162.49 43.09 161.71 40.56 163.30 39.16 Z"/>
                    </svg>
                </a>
            </div>
        </div>

        <div class="col-xs-12 col-md-7 top-search-holder no-margin">
            <div class="search-area">
                <form>
                    <div class="control-group">
                        <?= \kartik\select2\Select2::widget([
                            'name' => 'kv-repo-template',
                            'options' => [
                                'placeholder' => 'Поиск ...'
                            ],
                            'pluginOptions' => [
                                'allowClear' => false,
                                'minimumInputLength' => 1,
                                'ajax' => [
                                    'url' => "/api/search",
                                    'dataType' => 'json',
                                    'delay' => 250,
                                    'data' => new JsExpression('function(params) { return {q:params.term, page: params.page}; }'),
                                    'processResults' => new JsExpression('function (data, params) {params.page = params.page || 1;return {results: data.items,pagination: {more: (params.page * 30) < data.total_count}};}'),
                                    'cache' => true
                                ],
                                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                                'templateResult' => new JsExpression('formatRepo'),
                            ],
                        ]); ?>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xs-12 col-md-2">
            <div class="btn btn-success default-button search-offers">
                <div class="control-group">
                    <span class="glyphicon glyphicon-search" style="color:#fff!important;"></span>
                    Поиск
                </div>
            </div>
        </div>
    </div>

    <?= $this->render('_menu'); ?>

    <?php
    $model = (new \common\models\Offers());
    $form = \yii\widgets\ActiveForm::begin([
        'method' => 'post',
        'action' => ['/site/search'],
        'id' => 'form-search'
    ]);
    ?>
    <?= $form->field($model, '_search')->hiddenInput(['class' => 'input-search'])->label(false); ?>
    <?= \yii\helpers\Html::submitButton('Отправить', ['class' => 'submit-form-search']) ?>
    <?php \yii\widgets\ActiveForm::end(); ?>

</header>